### ISSUE TITLE
about RandAug

### ISSUE THREAD

**Issue by liaochuanlin** [LeapLabTHU/EfficientTrain#10]
Finally, we integrate the techniques proposed in Sections 4.1 and 4.2, and design a unified efficient training curriculum. In specific, we first set the magnitude m of RandAug to be a linear function of the training epoch t: m = (t/T )×m0, with other data augmentation techniques unchanged. Despite the simplicity, this setting yields consistent and significant empirical improvements. Note that we adopt m0 = 9 following the common practice [4], [18], [19], [20], [21].
Dear author, the above randaug is embodied in that piece of code?

**Comment by blackfeather-wang** [comment]
Thanks for your attention! This is implemented in the script level, for example, https://github.com/LeapLabTHU/EfficientTrain/blob/dd109a62da3c480f837b2af836d2d9f8e67543a5/_ET_pp_wReplay_main_deitS.py#L59
