### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by liaochuanlin** [LeapLabTHU/EfficientTrain#3]
Dear author, what about the greedy algorithm and frequency trimming implemented in that part of the code?

**Comment by blackfeather-wang** [comment]
Thank you for your attention to our work.

The code for low-frequency cropping can be found in the previous version of this repo.

The greedy-search algorithm is very simple, and can be implemented with the current code (by simply changing the cmds).

**Comment by liaochuanlin** [comment]
Dear author, I only found one version in this repository at https://github.com/LeapLabTHU/EfficientTrain, and there doesn't seem to be an earlier version.

**Comment by blackfeather-wang** [comment]
Thank you for the reply.

The original low-frequency cropping operation can be found at https://github.com/LeapLabTHU/EfficientTrain/commit/ef7d5f1c0951e6e625c40538e1802f86806256ca#diff-773b7e340b77c3c54109da863b41163ac971f899da59d8efcbfba7ce8a9c7e88R50

The current repo utilizes the improved efficient low-frequency down-sampling operation (as stated in our paper).

**Comment by liaochuanlin** [comment]
Thank you for the reply.
![Uploading image.png…]()
In this image transformation, I didn't find "First, we perform low-pass filtering on the original images with a B × B square filter (without changing the image size). Second, we perform B × B down-sampling." This operation is implemented in that python file? Looking forward to your reply!

**Comment by blackfeather-wang** [comment]
https://github.com/LeapLabTHU/EfficientTrain/blob/dd109a62da3c480f837b2af836d2d9f8e67543a5/datasets_buffer.py#L80

**Comment by blackfeather-wang** [comment]
It is implemented here: https://github.com/LeapLabTHU/EfficientTrain/blob/dd109a62da3c480f837b2af836d2d9f8e67543a5/datasets_buffer.py#L80

**Comment by blackfeather-wang** [comment]
It is implemented here: https://github.com/LeapLabTHU/EfficientTrain/blob/dd109a62da3c480f837b2af836d2d9f8e67543a5/datasets_buffer.py#L80

This two-step procedure can be elegantly integrated into the LANCZOS resampling algorithm. The 2D sinc convolution in LANCZOS is mathematically equivalent to low-pass filtering.

**Comment by liaochuanlin** [comment]
Thank you for the reply.
Dear author, could you please tell me if you have tried to train this strategy on a relatively small model with a single card?

**Comment by blackfeather-wang** [comment]
In fact, we do not try. However, according to our observation, EfficientTrain++ tends to be more effective for relatively smaller models. Hence, if you consider such scenarios, we believe that our strategy may still work.

**Comment by blackfeather-wang** [comment]
In fact, we did not try exactly the scenario you consider. However, according to our observation, EfficientTrain++ tends to be more effective for relatively smaller models. Hence, if you consider such scenarios, we believe that our strategy may still work.

**Comment by blackfeather-wang** [comment]
In fact, we did not try exactly the scenario you mentioned. However, according to our observation, EfficientTrain++ tends to be more effective for relatively smaller models. Hence, if you consider such scenarios, we believe that our strategy may still work.

**Comment by liaochuanlin** [comment]
Thank you very much for your reply, I will go ahead and try to understand the code that you have written.

**Comment by blackfeather-wang** [comment]
Thank you for your attention to our work：）
