### ISSUE TITLE
Where are the codes of frequency cropping and greedy-search algorithm?

### ISSUE THREAD

**Issue by yuncheng97** [LeapLabTHU/EfficientTrain#5]
I cannot find it in the current repo or anywhere else.

**Comment by blackfeather-wang** [comment]
Thank you for your attention to our work.

The code for low-frequency cropping can be found in the previous version of this repo (https://github.com/LeapLabTHU/EfficientTrain/commit/ef7d5f1c0951e6e625c40538e1802f86806256ca#diff-773b7e340b77c3c54109da863b41163ac971f899da59d8efcbfba7ce8a9c7e88R50). The current repo utilizes the improved efficient low-frequency down-sampling operation (as stated in our paper).

The greedy-search algorithm is very simple, and can be implemented with the current code (by simply changing the cmds).

**Comment by yuncheng97** [comment]
Thanks so much for your reply.
