### ISSUE TITLE
About low-pass filtering

### ISSUE THREAD

**Issue by whalien-902** [LeapLabTHU/EfficientTrain#6]
I can implement low-pass filtering of the image through the Fourier transform. Could you please explain how to perform the inverse Fourier Transform to obtain the low-pass filtered image, as shown in the figure in your paper?
![111](https://github.com/LeapLabTHU/EfficientTrain/assets/102122699/1e90bc0d-6bfe-4d6d-aa11-baabdf194f85)

**Comment by whalien-902** [comment]
How did you achieve the above inverse  Fourier  transformation?

**Comment by blackfeather-wang** [comment]
The code for inverse 2D DFT can be found within this function: https://github.com/LeapLabTHU/EfficientTrain/commit/ef7d5f1c0951e6e625c40538e1802f86806256ca#diff-773b7e340b77c3c54109da863b41163ac971f899da59d8efcbfba7ce8a9c7e88R50

**Comment by whalien-902** [comment]
When I perform low-pass filtering and downsampling using the code you provided, strange color blocks like those shown in the image appear. What could be the reason for this?
![ori_image](https://github.com/LeapLabTHU/EfficientTrain/assets/102122699/9485ab2b-8a72-4a34-8b98-6f9d4fbea5b2)  origin_image
![Uploading out.png…]()
output_image

**Comment by whalien-902** [comment]
![out](https://github.com/LeapLabTHU/EfficientTrain/assets/102122699/66e8cf11-d034-4a16-bf6b-e8981150d16f)
output_image

**Comment by blackfeather-wang** [comment]
I've not met exactly the same issue you encountered. It seems to be caused by upper/lower numerical overflow (e.g., when converting data formats).
